import type { Procedure } from "./types";

export const catalogProcedures: Procedure[] = [
  { id: "cat-aplicacao-de-bcaa", name: "Aplicação de BCAA", category: "Procedimentos Base", price: 300, averageCost: 50, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-bioestimulador-de-gluteo-2x-elleva-210", name: "Bioestimulador de Glúteo - 2X ELLEVA 210", category: "Bioestimulador", price: 3500, averageCost: 1600, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-bioestimulador-eleva-150", name: "Bioestimulador Eleva 150", category: "Bioestimulador", price: 2100, averageCost: 499.99, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-bioestimulador-eleva-210", name: "Bioestimulador Eleva 210", category: "Bioestimulador", price: 3000, averageCost: 762.99, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-bioestimulador-radiesse", name: "Bioestimulador Radiesse", category: "Bioestimulador", price: 2300, averageCost: 625.76, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-bioestimulador-rennova-diamond", name: "Bioestimulador Rennova Diamond", category: "Bioestimulador", price: 2100, averageCost: 418.99, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-bioestimulador-sculptra", name: "Bioestimulador Sculptra", category: "Bioestimulador", price: 2500, averageCost: 777.77, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-botox-dysport", name: "Botox Dysport", category: "Botox", price: 1300, averageCost: 464, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-botox-letybo-inferior", name: "Botox Letybo Inferior", category: "Botox", price: 1500, averageCost: 310, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-botox-letybo-superior", name: "Botox Letybo Superior", category: "Botox", price: 1300, averageCost: 310, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-consulta", name: "Consulta", category: "Consulta", price: 200, averageCost: 0, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-fios-de-pdo", name: "Fios de PDO", category: "Fios", price: 1300, averageCost: 308.76, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-fios-de-pdo-de-tracao-4-fios", name: "Fios de PDO de Tração (4 fios)", category: "Fios", price: 1900, averageCost: 150, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-fios-de-pdo-fillers-2-canulas", name: "Fios de PDO Fillers (2 canulas)", category: "Fios", price: 1300, averageCost: 172.5, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-lavieen", name: "Lavieen", category: "Laser", price: 800, averageCost: 120.76, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-lavieen-1-paciente", name: "Lavieen (1 paciente)", category: "Laser", price: 800, averageCost: 300, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-lavieen-area-menor-2pac", name: "Lavieen (área menor-2pac)", category: "Laser", price: 800, averageCost: 150, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-lavieen-face-2pac", name: "Lavieen (face/2pac)", category: "Laser", price: 800, averageCost: 150, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-microagulhamento-com-peeling", name: "Microagulhamento com peeling", category: "Peeling", price: 800, averageCost: 60, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-pdo-espiculado-fe-type-l-cannula", name: "PDO Espiculado FE Type L-cannula - (4 Fios/Blister)", category: "Fios", price: 2800, averageCost: 272.81, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-pdo-espiculado-moldado-sc-type-l-cannula", name: "PDO Espiculado moldado SC Type L-cannula - (4 Fios/Blister)", category: "Fios", price: 3100, averageCost: 565.31, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-pdo-multi-liso-l-cannula", name: "PDO Multi Liso L-cannula - (4 Fios/Blister)", category: "Fios", price: 1500, averageCost: 345.5, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-peeling-lha-la-peel", name: "Peeling Lha La Peel", category: "Peeling", price: 600, averageCost: 90, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-preenchedor-belotero-intense", name: "Preenchedor Belotero Intense", category: "Preenchedor", price: 1300, averageCost: 220.76, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-preenchedor-biogelis-volume", name: "Preenchedor Biogelis Volume", category: "Preenchedor", price: 1200, averageCost: 205, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-preenchedor-contuor", name: "Preenchedor Contuor", category: "Preenchedor", price: 1200, averageCost: 173.45, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-preenchedor-global", name: "Preenchedor Global", category: "Preenchedor", price: 1300, averageCost: 200, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-preenchedor-lift-lips-plus-lido", name: "Preenchedor lift lips plus lido", category: "Preenchedor", price: 1300, averageCost: 263.99, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-preenchedor-rennova-ultravolume", name: "Preenchedor Rennova Ultravolume", category: "Preenchedor", price: 1200, averageCost: 217.76, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-preenchedor-restylane-defyne", name: "Preenchedor Restylane Defyne", category: "Preenchedor", price: 1200, averageCost: 353.62, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-preenchedor-restylane-lift", name: "Preenchedor Restylane Lift", category: "Preenchedor", price: 1300, averageCost: 309, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-preenchedor-restylane-tradicional", name: "Preenchedor Restylane Tradicional", category: "Preenchedor", price: 1200, averageCost: 208, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-preenchedor-yvoire-volume", name: "Preenchedor Yvoire Volume", category: "Preenchedor", price: 1200, averageCost: 159.76, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-preenchimento-gluteos", name: "Preenchimento Gluteos", category: "Preenchimento", price: 1000, averageCost: 251.76, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-preenchimento-gluteos-combo-42ml", name: "Preenchimento Gluteos - COMBO 42ML", category: "Preenchimento", price: 6300, averageCost: 2709, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-protocolo-redefyne", name: "Protocolo Redefyne", category: "Protocolo", price: 400, averageCost: 50, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-protocolo-redefyne-plus", name: "Protocolo Redefyne Plus", category: "Protocolo", price: 550, averageCost: 75, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-ultraformer-contorno-inferior", name: "Ultraformer Contorno Inferior", category: "Ultraformer", price: 1800, averageCost: 450, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-ultraformer-full-face", name: "Ultraformer Full face", category: "Ultraformer", price: 3800, averageCost: 1050, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-ultraformer-olheira", name: "Ultraformer Olheira", category: "Ultraformer", price: 1200, averageCost: 320.76, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-ultraformer-papada", name: "Ultraformer Papada", category: "Ultraformer", price: 1800, averageCost: 450, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true },
  { id: "cat-ultraformer-pescoco", name: "Ultraformer Pescoço", category: "Ultraformer", price: 1800, averageCost: 450, professionalPercent: 70, notes: "Importado do catálogo PDF.", active: true }
];
